#!/usr/bin/env node

S = f => g => x => f(x)(g(x));
K = x => _ => x;

hello = S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S(S(S(K)(K))
    (K(S(S(K(S))(S(K(K))(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S
    (K)(K))))(K(S(K)(K)))))))))(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S)
    )(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))(S(K(S(K(S(K
    (S(K(S(S(K(S))(S(K(K))(S(S(K)(K))(K(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))
    )))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(
    S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))
    )))(K(S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K
    (K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(
    S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))))(S(
    K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K)
    )))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))
    (S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))))))(S(K
    (S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))
    ))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K
    ))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K
    )(K))))))))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K)
    )))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(
    K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S
    (S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))
    ))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))
    (S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S
    (K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(
    K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K)))))
    )))))))))))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S)
    )))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S)
    )))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(
    K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(
    K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(
    S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(
    K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S
    (K(S(K(K))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))
    )))(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(S(S(K)(K))))(S(K(K))(S(K)(K)))))))(K(S(K
    (K))(S(K)(K))))))))))))))))))))))))))))))(K(S(K(K))(S(K(K))(S(K(S(S(K(S))(S(
    K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(
    K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S)))
    )))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(S(K(
    S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))
    (K(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))))(S(S(K(S))(S(K(S(K(S))))(
    S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))
    ))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S
    (K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))
    ))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S
    ))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))
    ))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K
    ))))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K
    (K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))(K(S(K(S(K(S(K(S(K(
    S(K(S(S(K)(K))))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(S(K(S))(S(K(S(K(S
    ))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S
    (S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S)
    )))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K
    (S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K
    (K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))))))))))))))(S(K(
    S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S)
    )))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(
    S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(
    K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(
    S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K)
    )(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))
    ))))))))))(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))))(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(
    S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))
    (S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S
    (S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S)))
    )(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))
    ))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S
    (K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K
    (S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K
    (S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S
    (K(S(K(S(K(S(K(S(K(S))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))
    ))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K
    (S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K
    (S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))
    ))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(S(K(S
    ))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S
    (K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))(K(S(
    K(S(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S
    (K(K))))))))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S
    (K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))
    ))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))))))(S(K(K)
    )(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(
    S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))
    (K(S(K)(K)))))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K
    (S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K)))
    )(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(
    S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S
    (S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))
    )))))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S)
    )))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S)))
    )))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S)))
    )))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(
    K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(K))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(
    S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))(K(S(K(S(K(S(K(S(K(S(S(K)(
    K))))))))))(S(K(S(K(S(K(S(K(K))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(
    S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S
    (K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(
    S(K)(K)))))))(K(K(S(K)(K))))))))))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K
    (K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))
    (S(K(K))(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))
    ))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S
    ))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S
    (K(S))))))(S(K(S(K(S(K(K))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))
    )(K(S(K(S(S(K)(K))))(S(K(K))(S(K)(K))))))))))))))))))))))))))))))))))(S(K(S(
    S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(
    S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(
    S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(
    K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))(S(K(S(K(
    S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(
    S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S)))))))))))
    )))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(
    S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(
    S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S)))))))))))))))
    )))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(
    S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(
    K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(
    S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(S(K(S))(S(K(K))(S(
    K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K)
    )(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))(K(S(K(S(K(S(K(S(K
    (S(K(S(K(S(K(S(S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K)))))))))
    )))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(
    S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K)
    )))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))))))(S(K(K))(S(S(K(S))(S
    (K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K
    (K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))))
    )))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(
    K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))
    ))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K
    (K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(
    S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K
    )(K)))))))))))))))))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K
    (S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K
    (S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S
    (K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K
    (S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))
    ))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K
    (K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K
    (S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K
    (S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))
    ))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K
    (S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K
    (S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))
    (S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S
    (K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))
    ))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K
    ))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K
    ))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K)
    )))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))
    ))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K)))
    )(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))))))))(S(K(S(
    K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K)
    )))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(
    K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(
    S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K)
    )))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K)
    )(S(K(S))(S(K(K))(S(K)(K))))))))))))(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))(S(
    K(S(K(S(K(S(K(K))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(
    S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S
    ))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(
    K(K(S(K)(K))))))))))))))))))))))))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(K))))
    ))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))
    ))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K
    ))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))
    ))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K
    (S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K
    (S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))
    ))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K
    (S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K
    (S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))
    (S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K
    (S(K(S(K(K))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S
    ))(S(K(K))(S(K)(K))))))))))(K(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))
    ))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)
    (K)))))))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))))(S(K(S(K(S(K(K)))))
    )(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S)
    )))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(
    S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K)))
    )))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(
    S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(
    S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S)))))))
    )))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(
    S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(
    K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(
    S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(S(K(S))(S(
    K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))(K(S(K
    (S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(
    K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))
    ))))))))))))))))))))))(S(K(K))(S(K(K))(S(K(S(K(K))))(S(K(S(K(K))))(S(K(S(K(S
    (S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K
    (K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))
    (S(K(K))(S(K)(K))))))))))))))))))))))))))(S(K(S(K(K))))(S(K(S(K(S(S(K(S))(S(
    K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S)
    )(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))
    ))))))))))))(S(K(S(K(K))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K
    (S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))
    (S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S
    (K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))
    )))))))))))))))))))))(S(K(K))(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(
    S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(
    S(K)(K))))))))))))))))))))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K
    (S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))))))
    )))))))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K)
    )(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))(S
    (K(S(K(S(K(K))))))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K
    (K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(S(
    K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))
    ))))))(S(K(S(K(K))))(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K
    ))(S(K)(K))))))))))))(S(K(S(K(K))))(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(
    K(S))(S(K(K))(S(K)(K))))))))))(S(K(K))(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))
    (S(K)(K))))))))(S(K(K))(S(K(S(S(K(S))(S(K(K))(S(K)(K))))))(S(K(K))(S(K(S(S(K
    )(K))))(S(K(K))(S(K)(K))))))))))))))))))))))))))))))))))))))))))))))))))))))
    ))))))))(K(K(K(K(S(K(S(S(K)(K))))(S(K(K))(S(K)(K))))))));

printChar   = asc => rest => String.fromCharCode(asc) + rest;
emptyString = '';
succ        = x => x+1;
zero        = 0;
process.stdout.write(hello(printChar)(emptyString)(succ)(zero));
