#!/usr/bin/env python3

S = lambda f: lambda g: lambda x: f(x)(g(x))
K = lambda x: lambda _: x

hello = S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S(S(S(K)(K \
    ))(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K \
    ))(S(K)(K))))(K(S(K)(K)))))))))(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S( \
    S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))(S(K \
    (S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(S(K)(K))(K(S(S(K(S))(S(K(K))(S(K)(K))))(K \
    (S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(S(K(S))( \
    S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K) \
    )))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S \
    (K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K \
    )(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K) \
    )))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S( \
    K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))( \
    S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K) \
    (K))))))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K)) \
    ))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S \
    (S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K) \
    )(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))))))))(S(K(S(K(S(K(S(K( \
    S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K( \
    S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(S(K(S))(S( \
    K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S))(S(K(K))(S(K)(K))) \
    )(K(S(K)(K)))))(K(S(K)(K))))))))))))))))))))))))(S(K(S(K(S(K(S(K(S(S(K(S)) \
    (S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K \
    (S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K \
    (S))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(S(K(S))(S(S(K(S) \
    )(S(K(K))(S(K)(K))))(K(S(K)(K)))))(K(S(K)(K))))))))))))))))))))))))))(S(S( \
    K(S))(S(K(K))(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S) \
    )))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S( \
    K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S( \
    K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S( \
    K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S( \
    K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))) \
    )(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K)))) \
    ))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))(K(S(S( \
    K(S))(S(K(K))(S(K(S))(S(K(S(S(K)(K))))(S(K(K))(S(K)(K)))))))(K(S(K(K))(S(K \
    )(K))))))))))))))))))))))))))))))(K(S(K(K))(S(K(K))(S(K(S(S(K(S))(S(K(S(K( \
    S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))) \
    )(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))) \
    )(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(S(K( \
    S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))))) \
    ))(K(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))))(S(S(K(S))(S(K(S(K(S) \
    )))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K) \
    ))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S \
    (K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S \
    (K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S \
    (K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S \
    (K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S \
    (K(S(K(S(K(S(K(K))))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S \
    (K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))) \
    )(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))))(S(K(S(K(S(K(S(K(S(K(K)))))))) \
    ))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S \
    (K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S( \
    K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S( \
    S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S)) \
    ))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)) \
    )))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K( \
    S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K( \
    S))))))))(S(K(S(K(S(K(S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K( \
    S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K( \
    S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S( \
    K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))) \
    )))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K( \
    K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))(K(S(K(S(K(S(K(S(K \
    (S(K(S(S(K)(K))))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(S(K(S))(S(K(S( \
    K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K) \
    )))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K \
    (S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K \
    )(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S( \
    S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K))))))))))))))))))))) \
    ))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K \
    (S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S)))))) \
    ))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S)))) \
    ))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S \
    (K(S(K(S(K(S))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S)))))))) \
    ))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K \
    (S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S \
    (K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S)))))) \
    ))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(S(K \
    (S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K \
    ))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))) \
    )(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))))))))(S(K(S(K(S(K(S(K(S \
    (K(S(K(S(K(K))))))))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S \
    ))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K)))) \
    (S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))) \
    )))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S( \
    K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))( \
    S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S \
    (K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K \
    (S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))) \
    )(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K \
    (S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S \
    (K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))))))))))))))) \
    )))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))) \
    )(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K( \
    S(K(K))))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S( \
    K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K( \
    S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S( \
    K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K( \
    S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S( \
    K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(S( \
    K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K( \
    K))(S(K)(K))))))))))))(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))(S(K(S(K(S(K(S( \
    K(K))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K) \
    )))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S \
    (K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S( \
    K)(K))))))))))))))))))))))))))))))))))(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K \
    ))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S)) \
    (S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K \
    (K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S \
    (K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S)))))) \
    (S(K(S(K(S(K(K))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))(K(S(K( \
    S(S(K)(K))))(S(K(K))(S(K)(K))))))))))))))))))))))))))))))))))(S(K(S(S(K(S) \
    )(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K( \
    S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S) \
    )))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S( \
    K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))(S(K(S( \
    K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K( \
    S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))) \
    )))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K( \
    S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S( \
    K(S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))) \
    )))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))(S( \
    K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))))))(S(K(S(K(S(K(S(K(S(K( \
    S(K(S(K(S(K(S(K(K))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S) \
    )))))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))))))( \
    S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))( \
    S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))))))))) \
    ))))))(K(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K))))))))))))))))(S(K(S(K(S(K( \
    S(K(S(K(S(K(S(K(K))))))))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K( \
    S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K( \
    K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))) \
    ))))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S \
    (K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K \
    (S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S) \
    )))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))( \
    S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K \
    (S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K) \
    )))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K( \
    S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K))))))))))))))))))))))))) \
    ))))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S \
    (K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K)) \
    ))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S)) \
    ))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K \
    (S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S \
    (K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K)))))))))))))) \
    (S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K \
    ))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K \
    (S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))))(S \
    (K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(S)) \
    ))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(K(S(K(S(K(S \
    (K(S(K(S(K(S))))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(S \
    (K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K \
    (K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))(K(S(K(S(K(S(K(S(K(S(K(S(S(K)(K)) \
    ))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K \
    (K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S \
    (K(K))(S(K)(K))))(K(S(K)(K)))))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K( \
    S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)( \
    K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K)) \
    (S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))) \
    )))))(S(K(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S) \
    )))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(S(K(S) \
    )))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(S(K(S))))))))(S( \
    K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K(S( \
    K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S(K( \
    S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))(S( \
    K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))))( \
    S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))))) \
    )(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))))) \
    )))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))))) \
    )))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(K(S(K(S(K(S(K(S(K(S(K(S))))) \
    )))))))(S(K(S(K(S(K(S(K(S(K(S(K(K))))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S( \
    K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))(K \
    (S(K(S(K(S(K(S(K(S(S(K)(K))))))))))(S(K(S(K(S(K(S(K(K))))))))(S(S(K(S))(S( \
    K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S( \
    K)(K))))(K(S(K)(K)))))))))(S(K(K))(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S \
    (S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))(K(K(S(K)(K)))))))))))))))))))) \
    ))))))))))))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S \
    (K(S(K(K))))))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K(S))))))(S(K \
    (S(K(S(K(K))))))(S(K(S(K(S(K(S))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(K(S)))) \
    ))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S \
    (K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K)) \
    ))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S \
    (K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K \
    (S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S \
    ))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S)))))))))) \
    (S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S \
    (K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K \
    (K))))))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K \
    (K))(S(K)(K))))))))))(K(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))))(S \
    (S(K(S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K \
    )))))))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))))(S(K(S(K(S(K(K))))) \
    )(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(S(K(S))(S(K(S(K(S))))(S(K(S(K(S(K( \
    S))))))(S(K(S(K(S(K(S(K(S))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K( \
    S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S( \
    K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))) \
    )))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S( \
    K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K( \
    S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))) \
    )))))(S(K(S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K( \
    S(K(S(K(S(K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S( \
    K(S(K(K))))))))))(S(K(S(K(S(K(S(K(S(K(S))))))))))(S(K(S(K(S(K(S(K(S(K(K))) \
    )))))))(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))( \
    S(K)(K))))))))))(K(S(K(S(K(S(K(S(S(K)(K))))))))(S(K(S(K(S(K(K))))))(S(S(K( \
    S))(S(K(S(K(S))))(S(K(S(K(K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K))))) \
    ))(K(K(S(K)(K)))))))))))))))))))))))))))))))))))(S(K(K))(S(K(K))(S(K(S(K(K \
    ))))(S(K(S(K(K))))(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K \
    ))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S)) \
    (S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))))))))))( \
    S(K(S(K(K))))(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S( \
    K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K( \
    K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))))))))(S(K(S(K(K))))(S(K(S(S(K \
    (S))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S)))) \
    (S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K \
    (S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K(K))))(S(K(S(K(S))))(S(K(S(K \
    (K))))(S(S(K(S))(S(K(K))(S(K)(K))))(K(S(K)(K)))))))))))))))))))))))(S(K(K) \
    )(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K) \
    )(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K)))))))))))))))))) \
    ))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S \
    (K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))))(S(K(S(K( \
    S(K(K))))))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))( \
    S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))))))(S(K(S(K(S(K(K)))) \
    ))(S(K(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S \
    (K(K))(S(K)(K))))))))))))))))(S(K(S(K(S(K(K))))))(S(K(S(K(S(S(K(S))(S(K(K) \
    )(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)(K))))))))))))))(S(K \
    (S(K(K))))(S(K(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K)( \
    K))))))))))))(S(K(S(K(K))))(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K(S))( \
    S(K(K))(S(K)(K))))))))))(S(K(K))(S(K(S(S(K(S))(S(K(K))(S(K(S))(S(K(K))(S(K \
    )(K))))))))(S(K(K))(S(K(S(S(K(S))(S(K(K))(S(K)(K))))))(S(K(K))(S(K(S(S(K)( \
    K))))(S(K(K))(S(K)(K)))))))))))))))))))))))))))))))))))))))))))))))))))))) \
    ))))))))(K(K(K(K(S(K(S(S(K)(K))))(S(K(K))(S(K)(K))))))))

print(hello (lambda ascii: lambda rest: chr(ascii) + rest) ('') (lambda x: x+1) (0), end='')
