#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

run() {
    language=$1
    codegen=$2
    file=helloworld/$3
    echo -n "$language"
    stack run hello-ski -- "$codegen" > "$file"
    chmod u+x "$file"
    "./$file"
}

run "Python 3:   " "python3"    hello.py
run "Ruby:       " "ruby"       hello.rb
run "Javascript: " "javascript" hello.js
run "Haskell:    " "haskell"    hello.hs
